### ISSUE TITLE
App not working with Koel v5

### ISSUE THREAD

**Issue by vmario89** [koel/app#51]
Hi,
since upgade from Koel 4 to 5 the app starts (login is fine) but search does not work and music does not play (infinite loading bar). I did a fresh recompile. Is it because the internal structure changed? Happy to get news about that. Using the desktop app for 2 years now and really missing it.

**Comment by phanan** [comment]
Hi @vmario89, sorry to hear about the breakage (and to respond this late). Truth is, the app isn't getting a lot of updates anymore. As the web version of Koel can now be installed as a PWA and works pretty much the same as a desktop app, it makes less and less sense to develop and maintain two different repositories. Personally, I've been using the PWA since forever:

![image](https://user-images.githubusercontent.com/8056274/129037864-f1889b6c-8996-4995-bc0b-54e1cec8f3e0.png)
